name: K6 Test Advanced Workflow

on:
  push:
    branches:
      - '**'

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1
        with:
          browser: true
          k6-version: "0.50.0"
      - name: Run local k6 test
        uses: grafana/run-k6-action@v1
        with:
          path: "*test.js"
          parallel: true
          fail-fast: true
          flags: "--vus 10"
